### PR TITLE
Dataset convenience methods

### PR DESCRIPTION
**Pull request by rimadoma**
Added _default_ methods introduced by Java 8 to the _Dataset_ interface for convenience.

### CODE REVIEW

**Comment by ctrueden** [comment]
The `imagej-common` library is currently still using Java 6. I'm surprise your IDE let you do this...?

**Comment by rimadoma** [comment]
Well it didn't really "let" me - I went ahead and changed the language level in the project settings...

Shall we leave this pull request pending for when the library adopts Java 8?

**Comment by rimadoma** [comment]
Would it actually make more sense to add these methods as static members of the _DatasetUtils_ class?

**Comment by hadim** [comment]
I was about to submit a similar PR when I found this one !

@rimadoma Could you also add methods to get axis ? Example : 

For now we have to do this to get calibration : 

```
dataset.axis(dataset.dimensionIndex(Axes.X)).calibratedValue(1)
```

Something like this would nicer : 

```
dataset.getAxis(Axes.X).calibratedValue(1)
// or 
dataset.axis(Axes.X).calibratedValue(1)
```

**Comment by rimadoma** [comment]
@hadim
I would prefer writing these functions as
```java
default Optional<CalibratedAxis> getAxis(AxisType axisType) {
    final int index = dimensionIndex(axisType);

    if (index < 0) {
        return Optional.empty();
    }
		
    return Optional.of(this.axis(index));
}
```

And like with this commit the problem is that `Optional` is a feature of Java 8, and afaik `imagej-common` isn't there yet. Furthermore the `Dataset` class is undergoing some major changes, and I feel like the time to add syntactic sugar is when the design stabilises.

**Comment by hadim** [comment]
I'm fine with this way of doing it. Let's wait for this repo ti be Java 8 ready then.

Can you add the method to your PR ? Or do you want me to submit a new PR ?

**Comment by rimadoma** [comment]
@hadim 
I'll go ahead and add it to this PR :)

**Comment by ctrueden** [comment]
We will switch everything to Java 8 imminently. ImgLib2 is switching now, so I will also switch SciJava Common and ImageJ Common. So hopefully we can stop ignoring this PR very soon. ;-)

**Comment by hadim** [comment]
Nice.

**Comment by ctrueden** [comment]
Rebased, cleaned up, and merged! Thanks @rimadoma.

I did change some of the behavior though:

* I used the names `dimension(AxisType)` and `axis(AxisType)` for consistency with the existing ImgLib2 API. I left the XYZCT convenience method accessor names alone (`getWidth` etc.).
* Calling `dimension(AxisType)` on a non-existent axis returns 1, not -1. This is consistent with ImageJ 1.x, where e.g. asking for the number of time points never returns 0 or negative. I also think it reduces case logic in downstream code, in general. If you really _need_ to distinguish whether a particular axis type is really there, then just ask for it directly using `axis(AxisType)`.

**Pull request closed without merging**
