### PR TITLE
ImgPlus support

### PR DESCRIPTION
**Pull request by hinerm**
Add better support for ImgPlus, allowing automatic Dataset > ImgPlus conversion active ImgPlus preprocessing.

### CODE REVIEW

**Comment by hinerm** [comment]
@ctrueden OK with you?

**Comment by ctrueden** [comment]
Seems good. Minor comments:
* Do we need the converter implementation right now? Or did you just add that proactively? If we need it, OK. It's lossy though, so if we don't acutely need it, I'd vote for waiting to include it till the convert framework supports this distinction (see also imagej/imagej-ops#103).
* Should we (do we?) have `Dataset` :arrow_right: `Img` and/or `ImgPlus` :arrow_right: `Img` as well?

**Comment by hinerm** [comment]
I started `Dataset > Img` [on this branch](https://github.com/imagej/imagej-common/tree/img-support). It would make sense to include `ImgPlus > Img` there as well.

They are useful converters.. I needed `Dataset > Img` on my op browser topic branch. But was holding off to specialize the converters for Img type.

The `Dataset > ImgPlus` converter was proactive. I figured since it's doing the same thing as the preprocessor then it makes sense. And actually it might be more reasonable for the preprocessor to just use the convert service.

**Comment by ctrueden** [comment]
> And actually it might be more reasonable for the preprocessor to just use the convert service.

There's any idea: generalize the single-input image preprocessor to ask the convert service: for _any_ given single-input type, can you convert the active `Dataset` and/or `DatasetView` and/or `ImageDisplay` to that type? If so, do it, and fill the result into that single input.

This might avoid a proliferation of highly specific single-input preprocessors... what do you think?

**Comment by hinerm** [comment]
>This might avoid a proliferation of highly specific single-input preprocessors... what do you think?

I like this idea.

**Comment by hinerm** [comment]
>I like this idea.

@ctrueden I think this should possibly be a future issue. At the least it requires an update to the `ConvertService` to add a `getCompatibleOutputs` method. Probably also a change to the `ModuleService` that lets `getSingleInput`/`getSingleOutput` take a list of classes.

**Comment by hinerm** [comment]
>Probably also a change to the ModuleService that lets getSingleInput/getSingleOutput take a list of classes.

@ctrueden OK, see https://github.com/scijava/scijava-common/pull/228

**Comment by ctrueden** [comment]
So, next steps for this PR now that scijava/scijava-common#228 is merged: cut a new release of scijava-common, pin it here, and use that as the foundation as discussed above?

**Pull request merged**
